bias_val:
- 0
bias_z: 4
channel:
- 1
checkpoint_hist: 1
data_path:
- /ed10/ed10.csv
data_size: 0
dataset: realPsf
epochs: 500
folder_name: ed10_ch1
image_size: 128
infer: true
lr: 0.0005
npts: 745
num_zernike: 24
output: ''
resume_path: /models/ed10/inputChannels/ch1/model_best.pth.tar
save_every: 50
seed: 0
test_size: 0.1
threads: 8
train_batch: 64
train_size: 1.0
val_size: 0.1
valid_batch: 64
z_range: 1
zernike:
- 3
- 5
- 6
- 7
- 8
- 9
- 10
- 11
- 12
- 13
- 14
- 15
- 16
- 17
- 18
- 19
- 20
- 21
- 22
- 23
- 24
- 25
- 26
- 27
